project:
  type: website

website:
  title: "Quarto website with freeze"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute: 
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
